services:
  mysql:
    image: mysql:latest
    container_name: app-database
    environment:
      MYSQL_ROOT_PASSWORD: P4sSw0rd0!
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "8080:80"
    depends_on:
      - mysql
