// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRlEA0M3uRurOpLHGdRDrtLKxx7DnD7cI',
    appId: '1:681638382675:web:c44f06f4b9d77547b98aa6',
    messagingSenderId: '681638382675',
    projectId: 'iti-chat-app-e55ae',
    authDomain: 'iti-chat-app-e55ae.firebaseapp.com',
    storageBucket: 'iti-chat-app-e55ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWZazCQrUIyzFchaYqMstxWUsf2AIThs',
    appId: '1:681638382675:android:dd3293d7eaab4c5bb98aa6',
    messagingSenderId: '681638382675',
    projectId: 'iti-chat-app-e55ae',
    storageBucket: 'iti-chat-app-e55ae.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpb6pmxmF-NQ1-UP41XS7eJwL-HSK4SCM',
    appId: '1:681638382675:ios:b004caeaa6ffa6b6b98aa6',
    messagingSenderId: '681638382675',
    projectId: 'iti-chat-app-e55ae',
    storageBucket: 'iti-chat-app-e55ae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpb6pmxmF-NQ1-UP41XS7eJwL-HSK4SCM',
    appId: '1:681638382675:ios:b004caeaa6ffa6b6b98aa6',
    messagingSenderId: '681638382675',
    projectId: 'iti-chat-app-e55ae',
    storageBucket: 'iti-chat-app-e55ae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRlEA0M3uRurOpLHGdRDrtLKxx7DnD7cI',
    appId: '1:681638382675:web:907cd9a86c73ad0fb98aa6',
    messagingSenderId: '681638382675',
    projectId: 'iti-chat-app-e55ae',
    authDomain: 'iti-chat-app-e55ae.firebaseapp.com',
    storageBucket: 'iti-chat-app-e55ae.firebasestorage.app',
  );
}
